# ci/minio-values.yaml
loki:
  image:
    registry: registry.cn-beijing.aliyuncs.com
    repository: xxk8s/loki
    tag: 2.5.0
    pullPolicy: IfNotPresent

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 2
  authEnabled: false

# Configuration for the write
write:
  # -- Number of replicas for the write
  replicas: 3
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.writeSelectorLabels" . | nindent 12 }}
            topologyKey: kubernetes.io/hostname
  persistence:
    size: 10Gi
    storageClass: rook-ceph-block-test1

# Configuration for the read node(s)
read:
  # -- Number of replicas for the read
  replicas: 3
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "loki.readSelectorLabels" . | nindent 12 }}
            topologyKey: kubernetes.io/hostname
  persistence:
    size: 10Gi
    storageClass: rook-ceph-block-test1

# Configuration for the gateway
gateway:
  enabled: true
  image:
    registry: registry.cn-beijing.aliyuncs.com
    repository: xxk8s/nginx-unprivileged
    tag: 1.19-alpine
    pullPolicy: IfNotPresent

# -------------------------------------
# Configuration for `minio` child chart
# -------------------------------------
minio:
  enabled: true
  accessKey: enterprise-logs
  secretKey: supersecret
  service:
    type: NodePort
    nodePort: 32000
  buckets:
    - name: chunks
      policy: none
      purge: false
    - name: ruler
      policy: none
      purge: false
    - name: admin
      policy: none
      purge: false
  persistence:
    size: 100Gi
    storageClass: rook-ceph-block-test1
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
