kind: Service
apiVersion: v1
metadata:
  name: mysql-external
  namespace: test-pod
  labels:
    app: mysql-external
spec:
  ports:
    - name: tcp-mysql-external
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: NodePort
