kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: test-pod
  labels:
    app: mysql
spec:
  ports:
    - name: tcp-mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
  type: ClusterIP
